//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id_productos { get; set; }
        public System.DateTime fecha { get; set; }
        public sbyte estatus { get; set; }
        public string nombre { get; set; }
    }
}
